### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [obedmr/corba#1]
please tell me this is like some old home work that you just decided to put on github. I'm having a hard time understanding why anybody would use corba anymore. I'm sure theres a brilliant reason for it if this is recent, but the only corba programmer I ever knew retired over 10 years ago.

I would think people would wanna use something a little more modern, like protocol buffers... or even just REST HTTP or DBus...or even just write something distributed in erlang or scheme...  feedback appreciated.

**Comment by obedmr** [comment]
Hi cloudkitsch, 
You may be surprised about it, but we did it on our recent Computer Science Master degree semester. We have been studying the history of Distributed Systems (CORBA was one of them). The professor just assigned us a simple 2 matrices multiplication example for comparing it with other more recent distributed systems solutions like JavaRMI (not so new, but newer) and other like Web Services and RestFUL APIs. We decided to add more fun on it and we implemented it over Vagrant/VirtualBox provided VMs. Feel free to comment or even use the code if you need something from there.

**Comment by ghost** [comment]
gotcha that makes sense. Yeah the word corba just came up for me today in a video I was watching and I thought "wow I haven't heard that in a long long time." I decided to see what I could find on github, and I noticed the repo being 18 days old roughly and thought "there's just no way something that old and esoteric is really making a comeback is it?" 

Also if you find you like the history of distributed systems:

http://en.wikipedia.org/wiki/Intel_Paragon

http://en.wikipedia.org/wiki/Transputer

http://en.wikipedia.org/wiki/OpenMosix

kdbus: https://www.youtube.com/watch?v=NgR6d54blrU

I'm a bit of a fan myself :)

**Comment by ghost** [comment]
A lot of decent ideas came from infernoOS and plan9 that are worthy of consideration as well.
